-- ============================================================================
-- FIX: Auto-generate UUID for user_profiles table
-- ============================================================================
-- This migration modifies the create_user_profile function to make the UUID
-- parameter optional and auto-generate it if not provided.
--
-- ISSUE:
-- - Users had to manually enter UUID when creating user profiles
-- - UUID should be auto-generated by the database
--
-- FIX:
-- - Make p_id parameter optional with DEFAULT gen_random_uuid()
-- - Auto-generate UUID if not provided
-- - Keep compatibility with existing code that passes UUID (e.g., from auth.users)
-- ============================================================================

-- Drop the existing function
DROP FUNCTION IF EXISTS create_user_profile(UUID, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT);

-- Recreate with optional UUID parameter (moved to END of param list)
CREATE OR REPLACE FUNCTION create_user_profile(
    p_role_id UUID,
    p_first_name TEXT,
    p_last_name TEXT,
    p_email TEXT,
    p_phone TEXT DEFAULT NULL,
    p_mobile TEXT DEFAULT NULL,
    p_id_number TEXT DEFAULT NULL,
    p_fsp_number TEXT DEFAULT NULL,
    p_status TEXT DEFAULT 'active',
    p_id UUID DEFAULT NULL  -- ✅ MOVED TO END - NOW OPTIONAL with auto-generation
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_new_id UUID;
BEGIN
    -- Validation
    IF p_first_name IS NULL OR p_first_name = '' THEN
        RETURN json_build_object('success', false, 'error', 'First name is required');
    END IF;
    
    IF p_last_name IS NULL OR p_last_name = '' THEN
        RETURN json_build_object('success', false, 'error', 'Last name is required');
    END IF;
    
    IF p_email IS NULL OR p_email = '' THEN
        RETURN json_build_object('success', false, 'error', 'Email is required');
    END IF;
    
    -- If p_id is NULL, generate a new UUID
    v_new_id := COALESCE(p_id, gen_random_uuid());

    -- Insert user profile
    INSERT INTO user_profiles (
        id, role_id, first_name, last_name, email, phone, mobile,
        id_number, fsp_number, status
    )
    VALUES (
        v_new_id, p_role_id, p_first_name, p_last_name, p_email, p_phone, p_mobile,
        p_id_number, p_fsp_number, p_status
    );
    
    RETURN json_build_object(
        'success', true, 
        'id', v_new_id,  -- Return the generated/provided ID
        'message', 'User profile created successfully'
    );
EXCEPTION
    WHEN unique_violation THEN
        RETURN json_build_object('success', false, 'error', 'Email already exists or UUID conflict');
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'Failed to create user profile: ' || SQLERRM);
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION create_user_profile TO authenticated;

-- ============================================================================
-- TESTING
-- ============================================================================
-- Test 1: Create user WITHOUT providing UUID (auto-generate)
-- SELECT create_user_profile(
--     p_role_id := 'some-role-uuid',
--     p_first_name := 'John',
--     p_last_name := 'Doe',
--     p_email := 'john.doe@example.com'
-- );
--
-- Test 2: Create user WITH explicit UUID (backward compatible)
-- SELECT create_user_profile(
--     p_id := 'specific-uuid-here',
--     p_role_id := 'some-role-uuid',
--     p_first_name := 'Jane',
--     p_last_name := 'Smith',
--     p_email := 'jane.smith@example.com'
-- );
-- ============================================================================

