-- ============================================================================
-- FIX: Auto-generate UUID for user_profiles table
-- ============================================================================
-- This migration modifies the create_user_profile function to make the UUID
-- parameter optional and auto-generate it if not provided.
--
-- ISSUE:
-- - Users had to manually enter UUID when creating user profiles
-- - UUID should be auto-generated by the database
--
-- FIX:
-- - Make p_id parameter optional with DEFAULT gen_random_uuid()
-- - Auto-generate UUID if not provided
-- - Keep compatibility with existing code that passes UUID (e.g., from auth.users)
-- ============================================================================

-- Drop the existing function (all possible signatures)
DROP FUNCTION IF EXISTS create_user_profile(UUID, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS create_user_profile(UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT);

-- Recreate with auto-generation for BOTH tables (public.users + user_profiles)
CREATE OR REPLACE FUNCTION create_user_profile(
    p_role_id UUID,
    p_first_name TEXT,
    p_last_name TEXT,
    p_email TEXT,
    p_phone TEXT DEFAULT NULL,
    p_mobile TEXT DEFAULT NULL,
    p_id_number TEXT DEFAULT NULL,
    p_fsp_number TEXT DEFAULT NULL,
    p_status TEXT DEFAULT 'active',
    p_id UUID DEFAULT NULL  -- ✅ OPTIONAL - auto-generates if NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user_id UUID;
    v_role_name TEXT;
BEGIN
    -- Validation
    IF p_first_name IS NULL OR p_first_name = '' THEN
        RETURN json_build_object('success', false, 'error', 'First name is required');
    END IF;
    
    IF p_last_name IS NULL OR p_last_name = '' THEN
        RETURN json_build_object('success', false, 'error', 'Last name is required');
    END IF;
    
    IF p_email IS NULL OR p_email = '' THEN
        RETURN json_build_object('success', false, 'error', 'Email is required');
    END IF;
    
    -- Get role name for public.users table
    SELECT role_name INTO v_role_name
    FROM user_roles
    WHERE id = p_role_id;
    
    IF v_role_name IS NULL THEN
        v_role_name := 'user';
    END IF;
    
    -- ✅ Step 1: Create or use existing record in public.users
    IF p_id IS NULL THEN
        -- Auto-generate: Insert into public.users (UUID auto-generated by table default)
        INSERT INTO users (email, role, role_id, is_active)
        VALUES (p_email, v_role_name, p_role_id, (p_status = 'active'))
        RETURNING id INTO v_user_id;
    ELSE
        -- Use provided UUID: Check if exists in users, create if not
        SELECT id INTO v_user_id FROM users WHERE id = p_id;
        
        IF v_user_id IS NULL THEN
            -- Create with provided UUID
            INSERT INTO users (id, email, role, role_id, is_active)
            VALUES (p_id, p_email, v_role_name, p_role_id, (p_status = 'active'))
            RETURNING id INTO v_user_id;
        END IF;
    END IF;

    -- ✅ Step 2: Insert into user_profiles (using the UUID from users table)
    INSERT INTO user_profiles (
        id, role_id, first_name, last_name, email, phone, mobile,
        id_number, fsp_number, status
    )
    VALUES (
        v_user_id, p_role_id, p_first_name, p_last_name, p_email, p_phone, p_mobile,
        p_id_number, p_fsp_number, p_status
    );
    
    RETURN json_build_object(
        'success', true, 
        'id', v_user_id,
        'message', 'User profile created successfully'
    );
EXCEPTION
    WHEN unique_violation THEN
        RETURN json_build_object('success', false, 'error', 'Email already exists or UUID conflict');
    WHEN foreign_key_violation THEN
        RETURN json_build_object('success', false, 'error', 'Invalid role_id or foreign key constraint violation');
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'Failed to create user profile: ' || SQLERRM);
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION create_user_profile TO authenticated;

-- ============================================================================
-- TESTING
-- ============================================================================
-- Test 1: Create user WITHOUT providing UUID (auto-generate)
-- SELECT create_user_profile(
--     p_role_id := 'some-role-uuid',
--     p_first_name := 'John',
--     p_last_name := 'Doe',
--     p_email := 'john.doe@example.com'
-- );
--
-- Test 2: Create user WITH explicit UUID (backward compatible)
-- SELECT create_user_profile(
--     p_id := 'specific-uuid-here',
--     p_role_id := 'some-role-uuid',
--     p_first_name := 'Jane',
--     p_last_name := 'Smith',
--     p_email := 'jane.smith@example.com'
-- );
-- ============================================================================

